In [ ]:
import numpy as np


# Array Manipulation

In [ ]:
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
#get dimension
b.ndim


2

In [ ]:
#get shape
b.shape

(2, 3)

In [ ]:
#get type
a.dtype


dtype('int16')

In [ ]:
print(a.itemsize)
print(b.itemsize)

2
8


In [ ]:
#total size
print(a.nbytes)
print(b.nbytes)

6
48


In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
print(a[1,5])
print(a[1,-3])

13
12


In [ ]:
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
a[:, 2]

array([ 3, 10])

In [ ]:
#getting a lil more fancy [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [ ]:
a[1,5] = 20
print(a)
a[:,2] = 5
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
b[0,1,1]

np.int64(4)

In [ ]:
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
np.random.rand(2,4)

array([[0.6937457 , 0.81821259, 0.86172602, 0.72526202],
       [0.02043564, 0.21597157, 0.33903301, 0.0303247 ]])

In [ ]:
np.random.randint(-4,7,size = (3,3))

array([[ 1,  0, -1],
       [ 4, -2,  3],
       [ 2,  2, -1]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5))
print(output)
z = np.zeros((3,3))
z[1,1] = 9
print(z)
print(output[1:-1,1:-1])
output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)


[100   2   3]
[1 2 3]


In [ ]:
a= np.array([1,2,3,4])
a+2
a-2
a*2
print(a)

[1 2 3 4]


In [ ]:
a / 2




array([1., 2., 3., 4.])

In [ ]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [ ]:
a ** 2


array([ 1,  4,  9, 16])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# LINEAR ALGEBRA

In [ ]:
a = np.full((2,3),1)
print(a)
b = np.full((3,2),2)
print(b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


In [ ]:
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [ ]:
c = np.identity(3)
print(int(np.linalg.det(c)))

1


# STATISTICS


In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.min(stats, axis = 1)

array([1, 4])

In [ ]:
print(np.max(stats))

6


In [ ]:
np.sum(stats, axis = 0)

array([5, 7, 9])

# REORGANIZING ARRAYS


In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [ ]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])